name: CI - Test & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Lancer les tests avec couverture
      run: |
        pytest --cov=app --cov-report=term-missing

    - name: Enregistrer le rapport de couverture
      uses: actions/upload-artifact@v3
      with:
        name: couverture-tests
        path: .coverage
