name: CI - Test & Coverage

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        pip install httpx

    - name: Lancer les tests avec couverture
      run: |
        pytest --cov=app --cov-report=term-missing

    - name: Enregistrer le rapport de couverture
      uses: actions/upload-artifact@v4
      with:
        name: couverture-tests
        path: .coverage
    - name: Run tests
      run: |
        docker run --rm bookreview-api pytest
